name       : sxiv
version    : 24
release    : 1
source     :
    - https://github.com/muennich/sxiv/archive/v24.tar.gz : 511dc45d12962af9c31c3068ce6bca4b832a6263946b27befea49a48cf019110
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Simple X Image Viewer
description: |
    The primary goal of sxiv is to create an image viewer, which only has the most basic features required for fast image viewing. It has vi key bindings and works nicely with tiling window managers.
builddeps  :
    - pkgconfig(imlib2)
    - pkgconfig(libexif)
    - pkgconfig(x11)
    - pkgconfig(xft)
    - giflib-devel
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
