name       : sxiv
version    : 26
release    : 5
source     :
    - https://github.com/muennich/sxiv/archive/v26.tar.gz : a382ad57734243818e828ba161fc0357b48d8f3a7f8c29cac183492b46b58949
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Simple X Image Viewer
description: |
    The primary goal of sxiv is to create an image viewer, which only has the most basic features required for fast image viewing. It has vi key bindings and works nicely with tiling window managers.
builddeps  :
    - pkgconfig(imlib2)
    - pkgconfig(libexif)
    - pkgconfig(x11)
    - pkgconfig(xft)
    - giflib-devel
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
    %make_install -C icon PREFIX=/usr
    install -Dm00644 sxiv.desktop $installdir/usr/share/applications/sxiv.desktop
