name       : sxiv
version    : '25'
release    : 2
source     :
    - https://github.com/muennich/sxiv/archive/v25.tar.gz : 16d1aca1a179e1c0875844efe2e51cfa396a4403467c389f7e9221a733ae5e26
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Simple X Image Viewer
description: |
    The primary goal of sxiv is to create an image viewer, which only has the most basic features required for fast image viewing. It has vi key bindings and works nicely with tiling window managers.
builddeps  :
    - pkgconfig(imlib2)
    - pkgconfig(libexif)
    - pkgconfig(x11)
    - pkgconfig(xft)
    - giflib-devel
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
